apiVersion: v1
data:
  CORECLR_PROFILER: "{57e1aa68-2229-41aa-9931-a6e93bbc64d8}"
  CORECLR_ENABLE_PROFILING: "1"
  CORECLR_PROFILER_PATH: "/opt/appdynamics/libappdprofiler.so"
  APPDYNAMICS_AGENT_ACCOUNT_NAME: customer1
  APPDYNAMICS_AGENT_APPLICATION_NAME: DotNetApp
  APPDYNAMICS_AGENT_TIER_NAME: Web
  APPDYNAMICS_AGENT_REUSE_NODE_NAME: "true"
  APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX: "Node"
  APPDYNAMICS_CONTROLLER_HOST_NAME: <controller-host>
  APPDYNAMICS_CONTROLLER_PORT: "8090"
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: "true"
kind: ConfigMap
metadata:
  name: dotnet-config